version: '3.7'

volumes:
  node_modules:

services:

  back:
    build: ./back
    command: bash -c "FLASK_APP=main.py FLASK_DEBUG=1 python -m flask run --host 0.0.0.0"
    volumes:
      - ./back:/code/
    ports:
      - "5000:5000"

  front:
    build: ./front
    command: bash -c "gulp start"
    volumes:
      - ./front:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - back
